[package]
name = "emudeck_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
env_logger = "0.11.5"
futures = "0.3.31"
log = "0.4.22"
notify = "6.1.1"
fs_extra = "1.2"
